### ISSUE TITLE
Fix node 16 build error now 14 builds

### ISSUE THREAD

**Issue by curtisdelicata** [familytree365/nuxt#54]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/familytree365)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by 4-l-Clover** [comment]
https://github.com/nuxt/nuxt.js/issues/9722
